# Generated by Django 3.2.15 on 2023-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('address', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='адрес')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('updated_at', models.DateTimeField(verbose_name='изменен')),
            ],
        ),
    ]
