# Generated by Django 3.2.15 on 2023-08-16 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='изменен'),
        ),
    ]
