# Generated by Django 3.2.15 on 2023-08-08 13:02

from django.db import migrations
import phonenumber_field.modelfields
import phonenumber_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20230807_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, validators=[phonenumber_field.validators.validate_international_phonenumber], verbose_name='телефон'),
        ),
    ]
