# Generated by Django 3.2.15 on 2023-08-12 09:56

from django.db import migrations


def move_price_to_order_product(apps, sсhema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    orders = Order.objects.all().prefetch_related('products')
    for order in orders:
        for entry in order.orderproduct_set.all():
            entry.price = entry.product.price
            entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderproduct_price'),
    ]

    operations = [migrations.RunPython(move_price_to_order_product)]
