# Generated by Django 3.2.15 on 2023-08-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230812_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Новый'), (2, 'Собрать'), (3, 'Доставить'), (4, 'Выполнен')], default=1, verbose_name='статус'),
        ),
    ]
